version: '3.1'

services:
  paas:
    container_name: hamster-paas
    image: hamster-paas
    restart: always
    ports:
      - 9898:9898
    volumes:
      - ./.docker.env:/.env
    env_file:
      - ./.docker.env
    depends_on:
      - db
      - nginx
      - meilisearch

  db:
    container_name: hamster-paas-db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./compose/db_init:/docker-entrypoint-initdb.d
      - hamster-paas-db-data:/var/lib/mysql
    env_file:
      - ./.docker.env

  nginx:
    container_name: hamster-paas-nginx
    image: nginx
    ports:
      - 9912:80
    volumes:
      - ./compose/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./compose/nginx/log:/var/log/nginx

  meilisearch:
    container_name: hamster-paas-meilisearch
    image: getmeili/meilisearch:v1.0
    restart: always
    ports:
      - 7700:7700
    volumes:
      - hamster-paas-meilisearch-data:/meili_data

networks:
  default:
    name: hamster-paas-network

volumes:
  hamster-paas-db-data: {}
  hamster-paas-meilisearch-data: {}
