---
apiVersion: v1
kind: Service
metadata:
  name: hamster-paas-service
  namespace: hamster
spec:
  selector:
    app: hamster-paas
  type: NodePort
  ports:
    - name: hamster-paas-web
      protocol: TCP
      port: 9898
      targetPort: 9898
      nodePort: 30314
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hamster-paas
  name: hamster-paas
  namespace: hamster
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hamster-paas
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hamster-paas
    spec:
      containers:
        - image: hamstershare/hamster-pass:${hamster_paas_version}
          imagePullPolicy: Always
          name: hamster-paas
          env:
            - name: PORT
              value: "9898"
            - name: MEILI_SEARCH
              value: "http://hamster-paas-meilisearch-service:7700"
            - name: NGINX_LOG_PATH
              value: "/var/log/nginx/access.log"
            - name: ALINE_DB_USER
              value: "root"
            - name: ALINE_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hamster-aline
                  key: db_password
            - name: ALINE_DB_HOST
              value: "mysql"
            - name: ALINE_DB_PORT
              value: "3306"
            - name: ALINE_DB_NAME
              value: "aline"
            - name: MYSQL_DATABASE
              value: "paas"
            - name: MYSQL_USER
              value: "aline"
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hamster-aline
                  key: db_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hamster-aline
                  key: db_password
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: FROM_EMAIL
              value: "hamster@hamsternet.io"
            - name: EMAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hamster-aline
                  key: email_password
          resources: {}
          ports:
            - containerPort: 9898
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/nginx
              name: hamster-paas-nginx-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: hamster-paas-nginx-log
          persistentVolumeClaim:
            claimName: hamster-paas-nginx-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hamster-paas-nginx-service
  namespace: hamster
spec:
  selector:
    app: hamster-paas-nginx
  type: NodePort
  ports:
    - name: hamster-paas-nginx
      protocol: TCP
      port: 9912
      targetPort: 80
      nodePort: 30311
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hamster-paas-nginx
  name: hamster-paas-nginx
  namespace: hamster
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hamster-paas-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hamster-paas-nginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: hamster-paas-nginx
          resources: {}
          ports:
            - containerPort: 80
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: configmap-hamster-paas-nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - mountPath: /var/log/nginx
              name: hamster-paas-nginx-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: configmap-hamster-paas-nginx
          configMap:
            name: hamster-paas-nginx-config
        - name: hamster-paas-nginx-log
          persistentVolumeClaim:
            claimName: hamster-paas-nginx-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hamster-paas-nginx-pvc
  namespace: hamster
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hamster-paas-meilisearch-service
  namespace: hamster
spec:
  selector:
    app: hamster-paas-meilisearch
  type: NodePort
  ports:
    - name: hamster-paas-meilisearch
      protocol: TCP
      port: 7700
      targetPort: 7700
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hamster-paas-meilisearch
  name: hamster-paas-meilisearch
  namespace: hamster
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hamster-paas-meilisearch
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hamster-paas-meilisearch
    spec:
      containers:
        - image: getmeili/meilisearch:v1.0
          imagePullPolicy: Always
          name: hamster-paas-meilisearch
          resources: {}
          ports:
            - containerPort: 7700
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/nginx
              name: hamster-paas-nginx-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: hamster-paas-nginx-log
          persistentVolumeClaim:
            claimName: hamster-paas-nginx-pvc
